language: cpp
compiler:
  - gcc
env:
  - GCC_VER=4.6
  - GCC_VER=4.8
before_install:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -qq g++-4.8
  - if [ "$GCC_VER" = "4.8" ]; then export CXX="g++-4.8" CC="gcc-4.8" GCOV="gcov-4.8"; else export CXX="g++-4.6" CC="gcc-4.6" GCOV="gcov-4.6"; fi
script: 
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug .
  - make -j2
  - make test
  - mkdir gcov
  - find CMakeFiles/ -name "*.gc*" -exec mv {} gcov/ \;
  - $GCOV -d -o gcov gcov/*.gcda
  - coveralls -n -E ".*\.cpp"
after_script:
  - contrib/codeanalysis/runcppcheck.sh
notifications:
  email:
    recipients:
      - jason@emptycrate.com
    on_success: always
    on_failure: always
env:
  global:
    secure: eiaR6pXiiEpyB8+LLQ1NvZdl0Yylru1BLy9lMoHl+IpUNGGQGywmW/2WAn77rFfmR1OPA2qWQLfgPwgK0HxUA9HHlot9tre5QhiN2Lw8NOT8tCZ6tTm2+QntDBjBGJyal/knRvQkn/6qs6GxlXRerz4ArnnuPL1vESt3zwB0YtU=
