language: cpp


addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - g++-5
      - g++-6
  coverity_scan:
    project:
      name: "ChaiScript/ChaiScript"
      description: "Build submitted via Travis CI"
    notification_email: jason@emptycrate.com
    build_command_prepend: "cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug . "
    build_command:   "cmake --build . -- -j2"
    branch_pattern: coverity_scan
      
matrix:
  include:
    - os: linux
      sudo: false
      env: GCC_VER="4.9"
      compiler: gcc
      #    - os: linux
      #sudo: false
      #env: GCC_VER="6" CMAKE_OPTIONS="-D DYNLOAD_ENABLED:BOOL=FALSE -D MULTITHREAD_SUPPORT_ENABLED:BOOL=FALSE -D USE_STD_MAKE_SHARED:BOOL=TRUE" BUILD_ONLY=1
      #compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="5" CPPCHECK=1 CMAKE_OPTIONS="-D RUN_FUZZY_TESTS:BOOL=TRUE"
      compiler: gcc
    - os: linux
      sudo: false
      env: GCC_VER="6" CPPCHECK=1 COVERAGE=1 CMAKE_OPTIONS="-D RUN_FUZZY_TESTS:BOOL=TRUE"
      compiler: gcc
    - os: osx
      compiler: clang
      osx_image: xcode8
    - os: osx
      compiler: clang
      osx_image: xcode8
      env: CMAKE_OPTIONS="-D DYNLOAD_ENABLED:BOOL=FALSE -D MULTITHREAD_SUPPORT_ENABLED:BOOL=FALSE -D USE_STD_MAKE_SHARED:BOOL=TRUE" BUILD_ONLY=1
  
env:
  global:
    - secure: eiaR6pXiiEpyB8+LLQ1NvZdl0Yylru1BLy9lMoHl+IpUNGGQGywmW/2WAn77rFfmR1OPA2qWQLfgPwgK0HxUA9HHlot9tre5QhiN2Lw8NOT8tCZ6tTm2+QntDBjBGJyal/knRvQkn/6qs6GxlXRerz4ArnnuPL1vESt3zwB0YtU=
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    - secure: "LfolGjP8tWm3yAwthfu3yp8Zn40aueFae580UUR34gusG87cyglq2tQDtxdy+63gWEeNfArbv9n5rZv+bDW3ggHyPjuCKKc1PlZAy07lfXUXf1uz+SFhNvNoYTn3mQG3VZ08o116p4Le2p8yqu4bylJ8wckEq7PrTwvSGVQWTWM="

before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER" GCOV="gcov-$GCC_VER" ; fi
  - pip install --user cpp-coveralls

script: 
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE -D CMAKE_BUILD_TYPE:STRING=Debug $CMAKE_OPTIONS . 
  - cmake --build . -- -j2
  - if [ "${BUILD_ONLY}" != "1" ]; then ctest; fi
  - if [ "${COVERAGE}" = "1" ]; then bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -x $GCOV -a "-s `pwd`" ; fi

#after_script:
#  - if [ ${CPPCHECK} = 1 ]; then contrib/codeanalysis/runcppcheck.sh ; fi


notifications:
  email:
    recipients:
      - jason@emptycrate.com
    on_success: always
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4be9a2720eaa1bb2a6c9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
